version: "3.3"

networks:
  yingxue_network:

#volumes:
#  data:
#  redisdata:
#  mqdata:

services:
  nacos:
    image: nacos/nacos-server:2.0.2
    ports:
      - "8848:8848"
    environment:
      - "JVM_XMS=256m"
      - "JVM_XMX=256m"
      - "MODE=standalone"
    networks:
      - yingxue_network


#  mysql:
#    image: mysql:5.7
#    ports:
#      - "3306:3306"
#    networks:
#      - yingxue_network
#    volumes:
#      - data:/var/lib/mysql
#      - ./yingxue.sql:/docker-entrypoint-initdb.d/yingxue.sql
#    environment:
#      - "MYSQL_ROOT_PASSWORD=123"
#      - "MYSQL_DATABASE=yingxue"

#  redis:
#    image: redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - redisdata:/data
#
#  nginx:
#    image: nginx:1.21.1
#    ports:
#      - "80:80"
#    volumes:
#      - ./admin-dist:/usr/share/nginx/html:ro
#
#  rabbitmq:
#    image: rabbitmq:3.8-management
#    ports:
#      - "15672:15672"
#      - "5672:5672"
#    networks:
#      - yingxue_network
#    env_file:
#      - ./rabbitmq.env
#    volumes:
#      - mqdata:/var/lib/rabbitmq
#
#  es:
#    image: elasticsearch:6.8.0
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    volumes:
#      - ./ik/:/usr/share/elasticsearch/plugins/ik
#      - ./jvm.options:/usr/share/elasticsearch/config/jvm.options
#    networks:
#      - yingxue_network
#
#  kibana:
#    image: kibana:6.8.0
#    ports:
#      - 5601:5601
#    networks:
#      - yingxue_network
#    volumes:
#      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
#    depends_on:
#      - es
#



#  admins:
#    build:
#      context: ./images/admins
#      dockerfile: Dockerfile
#    ports:
#    - "8980:8980"
#    depends_on:
#      - mysql
#      - redis
#      - nacos
#
#  category:
#    build:
#      context: ./images/category
#      dockerfile: Dockerfile
#    ports:
#    - "8981:8981"
#    depends_on:
#      - mysql
#      - redis
#      - nacos
#
#  gateway:
#    build:
#      context: ./images/gateway
#      dockerfile: Dockerfile
#    ports:
#    - "9999:9999"
#    depends_on:
#      - mysql
#      - redis
#      - nacos
#
#  users:
#    build:
#      context: ./images/users
#      dockerfile: Dockerfile
#    ports:
#    - "8982:8982"
#    depends_on:
#      - mysql
#      - redis
#      - nacos
#
#  videos:
#    build:
#      context: ./images/videos
#      dockerfile: Dockerfile
#    ports:
#    - "8983:8983"
#    depends_on:
#      - mysql
#      - redis
#      - nacos

